### ISSUE TITLE
Proposal: Documentation Enhancement & Code Organization

### ISSUE THREAD

**Issue by johnbanq** [codehz/BedrockMod#1]
This is a project that is too good to exist without any docs on how to use it
Therefore,I propose a way to write docs & organize code for the various mod the project provides:

**Code Organization**
the code for each individual mod are placed in src/<MODNAME> 
eg: prop.cpp for chai_prop.so should be moved to src/prop/prop.cpp

**Documentation & Examples**
the docs and examples for a mod are placed in docs/<MODNAME> 
eg: docs and examples for chai_prop.so should be placed in docs/prop

**Pros**
the codebase will be more organized ,so it wont go too messy when we add more mods

**Cons**
the complexity of makefile will grow,since we must deal with sources behind the directories

**Examples**
I made a small example on the prop mod in my fork,feel free to check it out

**Comment by codehz** [comment]
Well, I'm going to find something alternative to Makefile, so I can reorganization without modify the fxxk Makefile... do you have some idea? (PS: I don't like to use cmake)
alternative to gnu make:
1. [xmake](https://github.com/tboox/xmake)
2. more...

**Comment by johnbanq** [comment]
Sorry for cant helping with that :( I am rather spoiled by IDE so I dunno which to choose neither

**Comment by codehz** [comment]
https://github.com/codehz/BedrockMod/commit/e5a58eed4c8ef5157b3813240c1277d71104ac88 
the build system has been restructuring
and the docs is coming soon

**Comment by johnbanq** [comment]
awesome,will wait for a example before helping with the docs

**Comment by codehz** [comment]
@johnbanq Wiki pages has been created!

**Comment by johnbanq** [comment]
THANKS!
