### ISSUE TITLE
Question: Reasons for adding Guile Support

### ISSUE THREAD

**Issue by johnbanq** [codehz/BedrockMod#3]
I wishes to know the reason for adding guile support for this scripting library.
since adding another language would mean more work in documentation and maintenance.
Was it simply due to personal taste or have other engineering concern?

After a quick glance through the reference manual,it is undeniable that this language has better documentation and more powerful in hooking.Also,this language is a extension of scheme,meaning that it gets the expressiveness and ease in DSL from Lisp-like languages.

But wont the lisp style be too esoteric to normal developers?Since FP is not something that a beginner can grab and go very quickly.

Note: I am NOT INTENDING TO START A FIGHT,just want to know why.Sorry if this triggers you.

**Comment by codehz** [comment]
@johnbanq I don't think chaiscript is more friendly for normal developer, as I learned more, I found that this language is really not a suitable plug-in language.
I have written more than 1500 lines code in chaiscript, I know that there so many thing that will "surprise" you.....
About the

**Comment by codehz** [comment]
And I think the scheme is a good choice for people who doesn't have any programming experience.

**Comment by codehz** [comment]
Another reason: ChaiScript is toooooo slow both runtime and compiling, although the former is not the main indicator.

**Comment by codehz** [comment]
About the chaiscript
Consider below code
```chaiscript
auto a = 1
def handle(int b) {
  a = a + b;
}
```
will failed, and you have to make `a` to be a global variable.
but the solution is not always works, for example
```
def test() {
  auto a = 0;
  def handle() {
    // how can I access the a?
  }
}
```
so you have to use the lambda (or bind)
But, if you want to make a recursive function with capturing outside variable...
You have to write like
```
def handle() {
    auto x = 0;
    var a = fun(){}
    a = fun[x, a](v) {
      // now you can access the lambda itself..
    }
}
```
**Yes, this is just a trivial issue. But similar issues are far more than this one in this language.** This makes it very difficult to create complex logic in this language.

**Comment by johnbanq** [comment]
thank you very much for answering and the example!
Yes,scheme is a good choice,both for beginners and the veterans(as long as they can get along with the odd syntax)
just for curious，why you didn't pick JavaScript?Is the engine it too heavy to integrate?

**Comment by johnbanq** [comment]
and are we moving away from chaiscript?

**Comment by codehz** [comment]
Yes, I have tried to embed the V8, but it is not easy to interact with c++, it DO has a friendly interface, but it require some compiler features that cannot to be used in GCC4.9 (I know it is too old, but upgrade the compiler will cause more problem about ABI)

**Comment by codehz** [comment]
Yes, I am going to publish my test scripts.

**Comment by johnbanq** [comment]
So we wont support python due to efficiency concern?

**Comment by codehz** [comment]
No, just because I am not familiar with python :)

**Comment by johnbanq** [comment]
Okay,thank you very much for answering these questions! It really helps in understanding what is going on! :D
