### ISSUE TITLE
1.7.0.13可以用这个mod吗？

### ISSUE THREAD

**Issue by 2252664145** [codehz/BedrockMod#7]
最新版的1.7.0.13可以0.3.1这个mod吗？如果可以的话，应该怎么用，这个mod有什么功能？有没有使用教程，可以出一个使用教程吗？谢谢！

**Comment by 2252664145** [comment]
windows版可以用这个mod吗？可以的话怎么启动？

**Comment by codehz** [comment]
@2252664145 不支持windows平台

**Comment by 2252664145** [comment]
@codehz 那么在ubuntu系统上应该解压到哪里？又应该怎么启动？没有使用说明吗？

**Comment by codehz** [comment]
@2252664145 https://gist.github.com/codehz/f7153de5a20d099aa18654a0edeb1f22 见最后getBDSM.sh

**Comment by 2252664145** [comment]
@codehz 我无法打开，你这个链接是被墙了吗？我需要翻墙？

**Comment by codehz** [comment]
@2252664145 是的

**Comment by 2252664145** [comment]
@codehz 不懂编程，我可以理解为直接运行getBDSM.sh就可以直接下载解压服务端和MOD吗？

**Comment by codehz** [comment]
@2252664145 是的

**Comment by 2252664145** [comment]
@codehz 启动指令还是官方的那个指令吗？

**Comment by codehz** [comment]
@2252664145 ./bdsm r -u

**Comment by 2252664145** [comment]
好的，我去试一下，谢谢你的解答

**Comment by 2252664145** [comment]
有新版本，或者你更新了MOD我可以直接运行getBDSM.sh直接更新吗？

**Comment by codehz** [comment]
@2252664145 yes

**Comment by 2252664145** [comment]
@codehz 也就是说要更改server.properties配置文件和备份地图需要进入到profiles/default目录进行操作？

**Comment by codehz** [comment]
@2252664145 升级不会覆盖这个，当然你愿意备份也没问题

**Comment by 2252664145** [comment]
basm-system.service   bdsm-user.service  这两个文件是干嘛的？需要和getBDSM.sh放在同一个目录吗？

**Comment by codehz** [comment]
@2252664145 用作后台服务的，不了解的就不用管了

**Comment by 2252664145** [comment]
好的，太感谢你了

**Comment by 2252664145** [comment]
@codehz 
`root@YGK:~# ./bdsm r
BDSM Version: v0.1.0-3-g5f438be
bedrock_server://root@YGK$ root@YGK:~# ./bdsm r -u
Failed to connect to session bus: exec: "dbus-launch": executable file not found in $PATH
`
这样是什么意思？无法运行吗？

**Comment by codehz** [comment]
@2252664145 安装dbus-x11

**Comment by 2252664145** [comment]
我输入`apt install dbus-x11`
任何再运行好像也不行
`root@YGK:~# ./bdsm r -u
BDSM Version: v0.1.0-3-g5f438be
bedrock_server://root@YGK$ root@YGK:~# 
`

**Comment by codehz** [comment]
@2252664145 可能是已知的不兼容问题

**Comment by 2252664145** [comment]
@codehz 已经运行了，游戏界面也显示在线人数0/10，信号也是满格，就是进不了世界是怎么回事？

**Comment by codehz** [comment]
@2252664145 检查本地网络问题

**Comment by 2252664145** [comment]
@codehz 本地没有问题，IP 47.94.108.54 端口19132,你可以帮我看一下吗？

**Comment by 2252664145** [comment]
大神帮帮忙啊，到底是哪里出问题了？官服可以运行，可以正常游戏，就这个可以运行不能连接进服务器
`root@YGK:~/mccs# ./bdsm r -u
BDSM Version: v0.1.0-3-g5f438be
ModLoader Loading...
Loading mod: libsupport
Loading mod: libbridge
Loading mod: libanti_cheats
Loading mod: libdisable_encryption
Loading mod: libedu
Loading mod: libscript
Loading mod: script_base
Loading mod: script_chat
Loading mod: script_command
Loading mod: script_config
Loading mod: script_dbus
Loading mod: script_fake
Loading mod: script_form
Loading mod: script_nbt
Loading mod: script_policy
Loading mod: script_server_exec
Loading mod: script_tick
Loading mod: script_transfer
Loading mod: script_world
D [run] setting up server logging...
D [run] Starting Server
D [run] Version 1.7.0.13 modded v0.3.1-5-g2052603
D [run] Level Name: Bedrock level
E [reload] Error opening whitelist file: profiles/default/whitelist.json
E [reload] Error opening ops file: ops.json
D [run] Game mode: 0 Survival
D [run] Difficulty: 1 EASY
D [LogIPSupport] IPv4 supported, port: 19135
D [LogIPSupport] IPv6 not supported
D [CMD] clear commands.clear.description 1 0 0
D [CMD] clone commands.clone.description 1 0 0
D [CMD] daylock commands.daylock.description 1 0 0
D [CMD] deop commands.deop.description 2 20 0
D [CMD] difficulty commands.difficulty.description 1 0 0
D [CMD] effect commands.effect.description 1 0 0
D [CMD] enchant commands.enchant.description 1 0 0
D [CMD] execute commands.execute.description 1 0 0
D [CMD] fill commands.fill.description 1 0 0
D [CMD] gamemode commands.gamemode.description 1 0 0
D [CMD] gamerule commands.gamerule.description 1 0 0
D [CMD] gettopsolidblock commands.gettopsolidblock.description 0 2 0
D [CMD] give commands.give.description 1 0 0
D [CMD] help commands.help.description 0 4 20
D [CMD] kill commands.kill.description 1 0 0
D [CMD] list commands.list.description 0 20 0
D [CMD] listd commands.listd.description 3 2 0
D [CMD] locate commands.locate.description 1 0 0
D [CMD] me commands.me.description 0 10 20
D [CMD] op commands.op.description 2 20 0
D [CMD] playsound commands.playsound.description 1 0 0
D [CMD] querytarget commands.querytarget.description 0 2 0
D [CMD] replaceitem commands.replaceitem.description 1 0 0
D [CMD] say commands.say.description 1 10 20
D [CMD] scoreboard commands.scoreboard.description 1 0 0
D [CMD] setblock commands.setblock.description 1 0 0
D [CMD] setmaxplayers commands.setmaxplayers.description 3 0 0
D [CMD] setworldspawn commands.setworldspawn.description 1 0 0
D [CMD] spawnpoint commands.spawnpoint.description 1 0 0
D [CMD] spreadplayers commands.spreadplayers.description 1 0 0
D [CMD] stopsound commands.stopsound.description 1 0 0
D [CMD] summon commands.summon.description 1 0 0
D [CMD] teleport commands.tp.description 1 0 0
D [CMD] tell commands.tell.description 0 10 20
D [CMD] testforblock commands.testforblock.description 1 0 0
D [CMD] testforblocks commands.testforblocks.description 1 0 0
D [CMD] testfor commands.testfor.description 1 0 0
D [CMD] tickingarea commands.tickingarea.description 1 0 0
D [CMD] time commands.time.description 1 0 0
D [CMD] title commands.title.description 1 10 0
D [CMD] toggledownfall commands.toggledownfall.description 1 0 0
D [CMD] weather commands.weather.description 1 0 0
D [CMD] wsserver commands.wsserver.description 2 8 0
D [CMD] xp commands.xp.description 1 0 0
D [CMD] ability commands.ability.description 1 0 0
D [CMD] immutableworld commands.immutableworld.description 1 0 0
D [CMD] worldbuilder commands.worldbuilder.description 1 0 0
D [CMD] agent commands.agent.description 1 2 0
D [CMD] kick commands.kick.description 4 0 0
D [CMD] save commands.save.description 4 0 0
D [CMD] stop commands.stop.description 4 0 0
D [CMD] whitelist commands.whitelist.description 4 0 0
D [CMD] permissions commands.permissions.description 4 0 0
D [CMD] ops commands.permissions.description 4 0 0
D [CMD] changesetting commands.changesetting.description 4 0 0
D [CMD] geteduserverinfo commands.geteduserverinfo.description 0 2 0
D [run] Server started.
Uncaught exception:
bedrock_server://root@YGK$  
`
