### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by KawaiiNahida** [codehz/BedrockMod#8]
无法启动，系统UBUNTU server 18.10
root@minecraft:/bdsm# ./bdsm r -u
Failed to connect to session bus: exec: "dbus-launch": executable file not found in $PATH

root@minecraft:/bdsm# ./bdsm r
BDSM Version: v0.1.0-3-g5f438be
ModLoader Loading...
Loading mod: libsupport
Loading mod: libbridge
bedrock_server://root@minecraft$

**Comment by MasterLuke117** [comment]
Thanks for the quick reply!!

Yes i did complete that step in the install guide, I also installed`dbus-x11` and it still won’t run

Luke,

**Comment by MasterLuke117** [comment]
root@server:/opt/bedrock# ./bdsm r -u
BDSM Version: v0.1.0-3-g5f438be
root@server:/opt/bedrock# ./bdsm r
BDSM Version: v0.1.0-3-g5f438be
root@server:/opt/bedrock# sudo ln -s /usr/lib/x86_64-linux-gnu/gconv /usr/lib/gconv
ln: failed to create symbolic link '/usr/lib/gconv/gconv': File exists
root@server:/opt/bedrock#

**Comment by WangYneos** [comment]
@MasteeLuke I found the way to fix it ,may be you should install the testing mods

**Comment by MasterLuke117** [comment]
Oh??   Testing mods? whats that exactly?

**Comment by MasterLuke117** [comment]
thats exactly what i have installed that wont run, i installed it per instructions at https://docs.bdsm.technology/

**Comment by WangYneos** [comment]
![image](https://user-images.githubusercontent.com/42824603/48616409-7e854c80-e9ce-11e8-80d5-a105aa0d5ffa.png)

**Comment by MasterLuke117** [comment]
Hmm!!  you have more files then i do in /scm
![screenshot 34 _li](https://user-images.githubusercontent.com/42286665/48617282-9d96c680-e95b-11e8-946e-efb7c2c6a4f4.jpg)

**Comment by WangYneos** [comment]
may be it can not run on WIP ,you should try install UBUNTU in vbox or vmware

**Comment by WangYneos** [comment]
can you speak Chinese , my English is not well can you communicate with me in Chinses?

**Comment by MasterLuke117** [comment]
im running ubuntu 18.04 , ill copy those files over and see if that fixes it

**Comment by WangYneos** [comment]
![image](https://user-images.githubusercontent.com/42824603/48617731-3bc57380-e9d2-11e8-9212-7539c360e23d.png)

**Comment by MasterLuke117** [comment]
![screenshot 34](https://user-images.githubusercontent.com/42286665/48618643-a5f10080-e95f-11e8-9c1d-a044b31b0ed4.png)

**Comment by codehz** [comment]
@WangYneos can you provide the output of the command `tree -d 3` (run it in base directory

**Comment by codehz** [comment]
Seems Linux distros' compatibility issue...(I tested it in archlinux
I will release a new version that use Linux container technical to fix that..

**Comment by MasterLuke117** [comment]
UPDATE:

I found the following out:
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-33-generic x86_64)  works fine with BDSM
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-39-generic x86_64)  Does not work!  BDSM will not run.

so i re-installed ubuntu 18 server, avoided running dist-upgrade and it works fine,
